import WebVRPolyfill from "webvr-polyfill";
import "./polyfill/audio.js";

if (window.Promise) {
    // IE11 does not support Promise, used by WebVRPolyfill, so don't create the fill to begin with (VR won't be supported anyway).
    var webvrPolyFill = new WebVRPolyfill();
}

export {ShaderLibrary} from "./shader/ShaderLibrary";

// generated by gulp
import "./../../build/tmp/shaderlib.js";

//
// root level API:
//

export {
    init, destroy, start, stop,
    META, capabilities,
    onPreFrame, onFrame,
	TextureWrapMode, TextureFilter, CullMode, StencilOp, Comparison, ElementType, BlendFactor, BlendOperation, ClearMask, InitOptions, TextureFormat, DataType, BufferUsage, CubeFace
} from "./Helix.js";

export { getVRDisplays, enableVR, disableVR } from "./vr/vr.js";

export { onGamepadConnected, onGamepadDisconnected, getGamepads, getGamepad } from "./input/gamepads.js";


//
// classes
//

export {Float2} from "./math/Float2";
export {Float4} from "./math/Float4";
export {CenteredGaussianCurve} from "./math/CenteredGaussianCurve";
export {MathX} from "./math/MathX";
export {Matrix4x4} from "./math/Matrix4x4";
export {PlaneSide} from "./math/PlaneSide";
export {PoissonDisk} from "./math/PoissonDisk";
export {PoissonSphere} from "./math/PoissonSphere";
export {Quaternion} from "./math/Quaternion";
export {Ray} from "./math/Ray";
export {SphericalHarmonicsRGB} from "./math/SphericalHarmonicsRGB";
export {Transform} from "./math/Transform";

export {Debug} from "./debug/Debug";
export {DebugAxes} from "./debug/DebugAxes";
export {ShowSkeleton} from "./debug/ShowSkeleton";

export {BoundingVolume} from "./scene/BoundingVolume";
export {BoundingAABB} from "./scene/BoundingAABB";
export {BoundingSphere} from "./scene/BoundingSphere";
export {FlatPartitioning} from "./scene/FlatPartitioning";
export {SceneNode} from "./scene/SceneNode";
export {Scene} from "./scene/Scene";
export {SceneVisitor} from "./scene/SceneVisitor";
export {Skybox} from "./scene/Skybox";
export {Terrain} from "./scene/Terrain";
export {QuadPartitioning} from "./scene/QuadPartitioning";

export {Entity} from "./entity/Entity";
export {EntityProxy} from "./entity/EntityProxy";
export {EntitySystem} from "./entity/EntitySystem";
export {EntitySet} from "./entity/EntitySet";
export {Component} from "./entity/Component";
export {CompositeComponent} from "./entity/CompositeComponent";

export {KeyFrame} from "./animation/KeyFrame";
export {AnimationClip} from "./animation/AnimationClip";
export {AnimationPlayhead} from "./animation/AnimationPlayhead";

export {LayeredAnimation} from "./animation/layered/LayeredAnimation";
export {AnimationLayer} from "./animation/layered/AnimationLayer";
export {AnimationLayerFloat4} from "./animation/layered/AnimationLayerFloat4";
export {AnimationLayerQuat} from "./animation/layered/AnimationLayerQuat";
export {AnimationLayerMorphTarget} from "./animation/layered/AnimationLayerMorphTarget";

export {MorphAnimation} from "./animation/morph/MorphAnimation";
export {MorphPose} from "./animation/morph/MorphPose";
export {MorphTarget} from "./animation/morph/MorphTarget";

export {Skeleton} from "./animation/skeleton/Skeleton";
export {SkeletonAnimation} from "./animation/skeleton/SkeletonAnimation";
export {SkeletonBinaryLerpNode} from "./animation/skeleton/SkeletonBinaryLerpNode";
export {SkeletonBlendNode} from "./animation/skeleton/SkeletonBlendNode";
export {SkeletonBlendTree} from "./animation/skeleton/SkeletonBlendTree";
export {SkeletonClipNode} from "./animation/skeleton/SkeletonClipNode";
export {SkeletonFreePoseNode} from "./animation/skeleton/SkeletonFreePoseNode";
export {SkeletonJoint} from "./animation/skeleton/SkeletonJoint";
export {SkeletonJointPose} from "./animation/skeleton/SkeletonJointPose";
export {SkeletonPose} from "./animation/skeleton/SkeletonPose";
export {SkeletonXFadeNode} from "./animation/skeleton/SkeletonXFadeNode";

export {AudioClip} from "./audio/AudioClip";
export {AudioDistanceModel} from "./audio/AudioDistanceModel";
export {AudioPanningModel} from "./audio/AudioPanningModel";
export {AudioEmitter} from "./audio/AudioEmitter";
export {AudioListener} from "./audio/AudioListener";

export {Camera} from "./camera/Camera";
export {CubeCamera} from "./camera/CubeCamera";
export {Frustum} from "./camera/Frustum";
export {PerspectiveCamera} from "./camera/PerspectiveCamera";
export {OrthographicCamera} from "./camera/OrthographicCamera";
export {OrthographicOffCenterCamera} from "./camera/OrthographicOffCenterCamera";
export {VRCamera} from "./camera/VRCamera";

export {Color} from "./core/Color";
export {DataStream} from "./core/DataStream";
export {GL} from "./core/GL";
export {Signal} from "./core/Signal";
export {Messenger} from "./core/Messenger";

export {Bloom} from "./effect/Bloom";
export {Blur} from "./effect/Blur";
export {CopyTexturePass} from "./effect/CopyTexturePass";
export {Effect} from "./effect/Effect";
export {EffectPass} from "./effect/EffectPass";
export {FilmicToneMapping} from "./effect/FilmicToneMapping";
export {Fog} from "./effect/Fog";
export {FXAA} from "./effect/FXAA";
export {GaussianBlurPass} from "./effect/GaussianBlurPass";
export {HBAO} from "./effect/HBAO";
export {SSAO} from "./effect/SSAO";
export {ReinhardToneMapping} from "./effect/ReinhardToneMapping";

export {Input} from "./input/Input";
export {Gamepad} from "./input/Gamepad";
export {Keyboard} from "./input/Keyboard";
export {Mouse} from "./input/Mouse";
export {MouseLock} from "./input/MouseLock";
export {Touch} from "./input/Touch";

export {AssetLibrary} from "./loaders/AssetLibrary";
export {AssetLoader} from "./loaders/AssetLoader";
export {URLLoader} from "./loaders/URLLoader";
export {AudioFile} from "./loaders/AudioFile";
export {ASH} from "./loaders/ASH";
export {DDS} from "./loaders/DDS";
export {HCM} from "./loaders/HCM";
export {HDR} from "./loaders/HDR";
export {HMAT} from "./loaders/HMAT";
export {HX} from "./loaders/HX";
export {Importer} from "./loaders/Importer";
export {JPG, PNG} from "./loaders/JPG_PNG";

export {AmbientLight} from "./light/AmbientLight";
export {DirectionalLight} from "./light/DirectionalLight";
export {Light} from "./light/Light";
export {DirectLight} from "./light/DirectLight";
export {LightProbe} from "./light/LightProbe";
export {PointLight} from "./light/PointLight";
export {SpotLight} from "./light/SpotLight";
export {FixedLightsSystem} from "./light/FixedLightsSystem";

export {ShadowFilter} from "./light/filters/ShadowFilter";
export {ExponentialShadowFilter} from "./light/filters/ExponentialShadowFilter";
export {HardShadowFilter} from "./light/filters/HardShadowFilter";
export {PCFShadowFilter} from "./light/filters/PCFShadowFilter";
export {VarianceShadowFilter} from "./light/filters/VarianceShadowFilter";

export {MaterialPass} from "./material/MaterialPass";
export {Material} from "./material/Material";
export {BasicMaterial} from "./material/BasicMaterial";
export {SkyboxMaterial} from "./material/SkyboxMaterial";
export {SkyboxSHMaterial} from "./material/SkyboxSHMaterial";

export {Mesh} from "./mesh/Mesh";
export {MeshInstance} from "./mesh/MeshInstance";
export {MeshBatch} from "./mesh/MeshBatch";

export {SpherePrimitive} from "./mesh/primitives/SpherePrimitive";
export {BoxPrimitive} from "./mesh/primitives/BoxPrimitive";
export {Primitive} from "./mesh/primitives/Primitive";
export {ConePrimitive} from "./mesh/primitives/ConePrimitive";
export {CylinderPrimitive} from "./mesh/primitives/CylinderPrimitive";
export {PlanePrimitive} from "./mesh/primitives/PlanePrimitive";
export {TorusPrimitive} from "./mesh/primitives/TorusPrimitive";
export {WireBoxPrimitive} from "./mesh/primitives/WireBoxPrimitive";
export {WirePlanePrimitive} from "./mesh/primitives/WirePlanePrimitive";

export {BlendState} from "./render/BlendState";
export {CubeRenderer} from "./render/CubeRenderer";
export {Renderer} from "./render/Renderer";
export {VRRenderer} from "./render/VRRenderer";
export {LightingModel} from "./render/LightingModel";
export {View, MultiRenderer} from "./render/MultiRenderer";
export {StencilState} from "./render/StencilState";

export {FrameBuffer} from "./texture/FrameBuffer";
export {Texture2D} from "./texture/Texture2D";
export {TextureCube} from "./texture/TextureCube";
export {TextureUtils} from "./texture/TextureUtils";
export {WriteOnlyDepthBuffer} from "./texture/WriteOnlyDepthBuffer";

export {AsyncTaskQueue} from "./utils/AsyncTaskQueue";
export {ArrayUtils} from "./utils/ArrayUtils";
export {BlitTexture} from "./utils/BlitTexture";
export {EquirectangularTexture} from "./utils/EquirectangularTexture";
export {HeightMap} from "./utils/HeightMap";
export {ImageData} from "./utils/ImageData";
export {MergeSpecularTextures} from "./utils/MergeSpecularTextures";
export {NormalTangentGenerator} from "./utils/NormalTangentGenerator";
export {Platform} from "./utils/Platform";
export {Raycaster} from "./utils/Raycaster";
export {StatsDisplay} from "./utils/StatsDisplay";

export {VRDisplay} from "./vr/VRDisplay";
